sudo: required
services:
  - docker

before_install:
  - docker build -t bpatz/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true  bpatz/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-804619810969"
  bucket_path: "docter-react"
  on:
    branch :master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"    